version: "3.9"
services:
  mysql-standalone-sa:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=student
    ports:
      - "3307:3306"
  springbatchapp-container:
    image: springboot-docker-container
    command: sh -c './wait_for_it.sh mysql-standalone-sa:3306 -- java -jar app.jar'
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone-sa:3306/student?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone-sa

networks:
  backing-services:
    driver: bridge